language: "en"
pipeline:
- name: "SpacyNLP"
  model: "en_core_web_md"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"

policies:
- name: "MemoizationPolicy"
- name: "TEDPolicy"
- name: "RulePolicy"
assistant_id: 20240228-231132-wide-sub
